name: E2E Tests

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cypress dependencies
        run: npm install

      - name: Install backend`
        working-directory: ./server
        run: npm install

      - name: Install frontend
        working-directory: ./client
        run: npm install

      - name: Start backend and frontend
        run: |
          npm run dev --prefix server &     # Port 3000
          npm run dev --prefix client &     # Port 5173
          npx wait-on http://localhost:3000 http://localhost:5173

      - name: Run Cypress tests
        run: npx cypress run
