name: Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  security:
    uses: ./.github/workflows/security.yml

  e2e:
    needs: [build]
    uses: ./.github/workflows/e2e.yml
